### ISSUE TITLE
Estimated BP

### ISSUE THREAD

**Issue by imAmitto** [Afonsocraposo/ppg#1]
value for `_bpm` is always 0.

**Comment by afonsocraposo** [comment]
Hi! Can you give more information?
For example, how does the signal shown in the graph?

**Comment by imAmitto** [comment]
@Afonsocraposo PR #2  should help. I have attached a video along with it which will help you understanding the problem.
Also, pardon my English.

**Comment by afonsocraposo** [comment]
@imAmitto Thank you for the videos. The condition you mentioned:
_bpm > 30 && _bpm < 150
Is there to avoid the display of incorrect bpm values, since the normal range of values for a healthy adult is between 60 and 90, and values smaller than 30 or greater than 150 would be very unlikely. Hope I could explain it :)

**Comment by imAmitto** [comment]
@Afonsocraposo I just removed them(temporarily) because i was using a sample video and yeah the condition is quite useful but i was thinking if a indicator can be added which can imply that the BPM is not normal.

**Comment by afonsocraposo** [comment]
It was fixed with the PR of @im-Amitto #2
